language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: JEKDtYgQKAhjtt9Lx4eMANGmPL62Uw9bPOcEVGnTlgO7ptl9gWFp8FRIl1xSxNYx+7ksvS1bqelltEWfVWTDOv9g6zlHYKlj7pmgwPn2ebpzILUQFtlMfTrqBixjrHYWNgOFgISf04eL0C6YMDaqiF7zuokthRX4ZWM7DKUVz93UInh9KnXDCdlwkOxPLvRPOSA8sBEmJFTIpnx+CGZwN520JiD9utEecsTZG9jg/8MADfGeco+kBgZncxZ2nsCvRgJNr/KUADxGkXVyQxI8TVL/KoUFrCxuX0N7tPW91rRcp2R3YsSJcTd+zaffUbD7xgvqaBMAPoy9fIkYDLOTbgRvdie7SReLZHAmSsB7dRI9FXwBI68I1s7npGVL2ZuOezE4fXxBI4gSdIsq0GnJw7SgosLn65AWbHF1ajx0rNjz5+WQ3rYEMjH+pCkTCTACbR4qkb4HWblpEdO9pvpjK6UtDP96WSQMBN+5262H9tsjNUB+kyNs+/pvqRRZvmnPskKqNY5hX5f+dxrtJ3TbDy7vRSn5zUW2dc1amJU24deJruhGGuhtkiYsp9FTArJCmzgwOv3EhLXRjEVWjMBhOKU5ztGGWfVkRLIYE5qBY90dvrqkgno570ZIoSBzYXM5glcJ6adzARjGaQ8zFFQvOjDqUKr+oI9rG+LEWh2iPOI=
  app: simplefolio-api
  on:
    repo: jeffbernst/simplefolio-api
